name: last_fm_app
description: A LastFM app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.0.4
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.0
  flutter_html: ^2.1.5
  hooks_riverpod: ^1.0.0
  meta: ^1.7.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  mocktail: ^0.2.0
flutter:
  uses-material-design: true
  assets:
    - .env
